import Head from "next/head";
// import Data from "@/components/Data";
import Data from "@/components/Data";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Weather App | Saul</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="md:flex md:justify-between w-full font-mono">
        <div className=" hidden h-screnn text-center md:flex justify-center mx-auto items-center bg-cyan-100/60 dark:bg-black dark:text-white w-1/2">
          <div>
            <div className="w-2/3 mx-auto space-y-5 mb-6">
              <p className="text-5xl">Welcome to my Weather App</p>
              <p>
                Here you can see some meteorological measurements in real time.
                I made this little app using Next.js and Tailwind CSS.
              </p>
            </div>
          </div>
        </div>
        <Data />
      </div>
      <Footer />
    </>
  );
}
